---
- hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - openssh-server
          - postfix
        state: present
        update_cache: yes
    - name: Download GitLab installer script
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: '0740'
    - name: Run GitLab installer script
      shell: ./script.deb.sh
      args:
        chdir: /tmp
    - name: Install GitLab CE
      apt:
        name: gitlab-ce
        state: present
    - name: Reconfigure GitLab
      shell: gitlab-ctl reconfigure
    - name: Set GitLab root password to 'SecDojo123'
      shell: |
        printf "SecDojo123\nSecDojo123\n" | gitlab-rake "gitlab:password:reset[root]"
      args:
        executable: /bin/bash
    - name: Get IMDSv2 token
      uri:
        url: http://169.254.169.254/latest/api/token
        method: PUT
        headers:
          X-aws-ec2-metadata-token-ttl-seconds: "21600"
        return_content: yes
      register: imds_token
    - name: Get EC2 instance public IP
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        method: GET
        headers:
          X-aws-ec2-metadata-token: "{{ imds_token.content }}"
        return_content: yes
      register: ec2_public_ip
    - name: Update GitLab external URL with EC2 public IP
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^external_url '.*'"
        line: "external_url 'http://{{ ec2_public_ip.content }}'"
        backup: yes
    - name: Reconfigure GitLab after URL change
      shell: gitlab-ctl reconfigure
    - name: Generate SSH key pair for CTF
      shell: ssh-keygen -t rsa -b 2048 -C "ctf_key" -f /tmp/ctf_key -N ""
      args:
        creates: /tmp/ctf_key
    - name: Add public key to root authorized_keys
      shell: cat /tmp/ctf_key.pub >> /root/.ssh/authorized_keys
    - name: Set correct permissions on authorized_keys
      file:
        path: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root
        group: root
    - name: Change ownership of SSH keys to git user
      file:
        path: "{{ item }}"
        owner: git
        group: git
        mode: '0600'
      loop:
        - /tmp/ctf_key
        - /tmp/ctf_key.pub