---
- name: Generate tokens and create env file
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run ctf_setup.rb script and capture output
      shell: gitlab-rails runner /tmp/ctf_setup.rb
      register: script_output
      changed_when: false

    - name: Extract CI token from output
      set_fact:
        ci_token: "{{ script_output.stdout | regex_search('Created personal access token for x-ci-bot: (\\S+)', '\\1') | first }}"

    - name: Extract Registry token from output
      set_fact:
        registry_token: "{{ script_output.stdout | regex_search('Created personal access token for x-registry-bot: (\\S+)', '\\1') | first }}"

    - name: Extract Runner token from output
      set_fact:
        runner_token: "{{ script_output.stdout | regex_search('Runner registration token for k8s-deployments: (\\S+)', '\\1') | first }}"

    - name: Validate tokens were extracted
      assert:
        that:
          - ci_token is defined and ci_token | length > 0
          - registry_token is defined and registry_token | length > 0
          - runner_token is defined and runner_token | length > 0
        fail_msg: "Failed to extract one or more tokens from script output"

    - name: Create local env.yml file
      copy:
        content: |
          # Auto-generated env.yml
          ci_bot_token: "{{ ci_token }}"
          registry_bot_token: "{{ registry_token }}"
          runner_registration_token: "{{ runner_token }}"
        dest: /tmp/env.yml
        mode: '0600'

    - name: Verify env.yml was created
      stat:
        path: /tmp/env.yml
      register: env_file

    - name: Display env.yml location and contents
      debug:
        msg: |
          env.yml created at: /tmp/env.yml
          Contents:
          {{ lookup('file', '/tmp/env.yml') }}
      when: env_file.stat.exists